/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedGoogleSheetsRouteImport } from './routes/_authenticated/google-sheets'
import { Route as AuthenticatedEarningsRouteImport } from './routes/_authenticated/earnings'
import { Route as AuthenticatedDeliveryRouteImport } from './routes/_authenticated/delivery'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedCallCenterRouteImport } from './routes/_authenticated/call-center'
import { Route as ApiCronGoogleSheetsRouteImport } from './routes/api/cron/google-sheets'
import { Route as AuthenticatedOrdersRowRouteImport } from './routes/_authenticated/orders.$row'
import { Route as AuthenticatedIntegrationTestIdRouteImport } from './routes/_authenticated/integration-test.$id'
import { Route as AuthenticatedCustomersPhoneRouteImport } from './routes/_authenticated/customers.$phone'
import { Route as ApiIntegrationsWidgetEndpointKeyRouteImport } from './routes/api/integrations/widget/$endpointKey'
import { Route as ApiIntegrationsWebhookEndpointKeyRouteImport } from './routes/api/integrations/webhook/$endpointKey'
import { Route as ApiIntegrationsPublicEndpointKeyRouteImport } from './routes/api/integrations/public/$endpointKey'
import { Route as ApiIntegrationsGoogleCallbackRouteImport } from './routes/api/integrations/google/callback'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGoogleSheetsRoute =
  AuthenticatedGoogleSheetsRouteImport.update({
    id: '/google-sheets',
    path: '/google-sheets',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEarningsRoute = AuthenticatedEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeliveryRoute = AuthenticatedDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCallCenterRoute = AuthenticatedCallCenterRouteImport.update({
  id: '/call-center',
  path: '/call-center',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiCronGoogleSheetsRoute = ApiCronGoogleSheetsRouteImport.update({
  id: '/api/cron/google-sheets',
  path: '/api/cron/google-sheets',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrdersRowRoute = AuthenticatedOrdersRowRouteImport.update({
  id: '/$row',
  path: '/$row',
  getParentRoute: () => AuthenticatedOrdersRoute,
} as any)
const AuthenticatedIntegrationTestIdRoute =
  AuthenticatedIntegrationTestIdRouteImport.update({
    id: '/integration-test/$id',
    path: '/integration-test/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersPhoneRoute =
  AuthenticatedCustomersPhoneRouteImport.update({
    id: '/$phone',
    path: '/$phone',
    getParentRoute: () => AuthenticatedCustomersRoute,
  } as any)
const ApiIntegrationsWidgetEndpointKeyRoute =
  ApiIntegrationsWidgetEndpointKeyRouteImport.update({
    id: '/api/integrations/widget/$endpointKey',
    path: '/api/integrations/widget/$endpointKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsWebhookEndpointKeyRoute =
  ApiIntegrationsWebhookEndpointKeyRouteImport.update({
    id: '/api/integrations/webhook/$endpointKey',
    path: '/api/integrations/webhook/$endpointKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsPublicEndpointKeyRoute =
  ApiIntegrationsPublicEndpointKeyRouteImport.update({
    id: '/api/integrations/public/$endpointKey',
    path: '/api/integrations/public/$endpointKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleCallbackRoute =
  ApiIntegrationsGoogleCallbackRouteImport.update({
    id: '/api/integrations/google/callback',
    path: '/api/integrations/google/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/call-center': typeof AuthenticatedCallCenterRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/delivery': typeof AuthenticatedDeliveryRoute
  '/earnings': typeof AuthenticatedEarningsRoute
  '/google-sheets': typeof AuthenticatedGoogleSheetsRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/products': typeof AuthenticatedProductsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/customers/$phone': typeof AuthenticatedCustomersPhoneRoute
  '/integration-test/$id': typeof AuthenticatedIntegrationTestIdRoute
  '/orders/$row': typeof AuthenticatedOrdersRowRoute
  '/api/cron/google-sheets': typeof ApiCronGoogleSheetsRoute
  '/api/integrations/google/callback': typeof ApiIntegrationsGoogleCallbackRoute
  '/api/integrations/public/$endpointKey': typeof ApiIntegrationsPublicEndpointKeyRoute
  '/api/integrations/webhook/$endpointKey': typeof ApiIntegrationsWebhookEndpointKeyRoute
  '/api/integrations/widget/$endpointKey': typeof ApiIntegrationsWidgetEndpointKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/call-center': typeof AuthenticatedCallCenterRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/delivery': typeof AuthenticatedDeliveryRoute
  '/earnings': typeof AuthenticatedEarningsRoute
  '/google-sheets': typeof AuthenticatedGoogleSheetsRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/products': typeof AuthenticatedProductsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/customers/$phone': typeof AuthenticatedCustomersPhoneRoute
  '/integration-test/$id': typeof AuthenticatedIntegrationTestIdRoute
  '/orders/$row': typeof AuthenticatedOrdersRowRoute
  '/api/cron/google-sheets': typeof ApiCronGoogleSheetsRoute
  '/api/integrations/google/callback': typeof ApiIntegrationsGoogleCallbackRoute
  '/api/integrations/public/$endpointKey': typeof ApiIntegrationsPublicEndpointKeyRoute
  '/api/integrations/webhook/$endpointKey': typeof ApiIntegrationsWebhookEndpointKeyRoute
  '/api/integrations/widget/$endpointKey': typeof ApiIntegrationsWidgetEndpointKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/call-center': typeof AuthenticatedCallCenterRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/delivery': typeof AuthenticatedDeliveryRoute
  '/_authenticated/earnings': typeof AuthenticatedEarningsRoute
  '/_authenticated/google-sheets': typeof AuthenticatedGoogleSheetsRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/customers/$phone': typeof AuthenticatedCustomersPhoneRoute
  '/_authenticated/integration-test/$id': typeof AuthenticatedIntegrationTestIdRoute
  '/_authenticated/orders/$row': typeof AuthenticatedOrdersRowRoute
  '/api/cron/google-sheets': typeof ApiCronGoogleSheetsRoute
  '/api/integrations/google/callback': typeof ApiIntegrationsGoogleCallbackRoute
  '/api/integrations/public/$endpointKey': typeof ApiIntegrationsPublicEndpointKeyRoute
  '/api/integrations/webhook/$endpointKey': typeof ApiIntegrationsWebhookEndpointKeyRoute
  '/api/integrations/widget/$endpointKey': typeof ApiIntegrationsWidgetEndpointKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/call-center'
    | '/customers'
    | '/dashboard'
    | '/delivery'
    | '/earnings'
    | '/google-sheets'
    | '/integrations'
    | '/orders'
    | '/products'
    | '/reports'
    | '/settings'
    | '/users'
    | '/customers/$phone'
    | '/integration-test/$id'
    | '/orders/$row'
    | '/api/cron/google-sheets'
    | '/api/integrations/google/callback'
    | '/api/integrations/public/$endpointKey'
    | '/api/integrations/webhook/$endpointKey'
    | '/api/integrations/widget/$endpointKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/call-center'
    | '/customers'
    | '/dashboard'
    | '/delivery'
    | '/earnings'
    | '/google-sheets'
    | '/integrations'
    | '/orders'
    | '/products'
    | '/reports'
    | '/settings'
    | '/users'
    | '/customers/$phone'
    | '/integration-test/$id'
    | '/orders/$row'
    | '/api/cron/google-sheets'
    | '/api/integrations/google/callback'
    | '/api/integrations/public/$endpointKey'
    | '/api/integrations/webhook/$endpointKey'
    | '/api/integrations/widget/$endpointKey'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/call-center'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/delivery'
    | '/_authenticated/earnings'
    | '/_authenticated/google-sheets'
    | '/_authenticated/integrations'
    | '/_authenticated/orders'
    | '/_authenticated/products'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/users'
    | '/_authenticated/customers/$phone'
    | '/_authenticated/integration-test/$id'
    | '/_authenticated/orders/$row'
    | '/api/cron/google-sheets'
    | '/api/integrations/google/callback'
    | '/api/integrations/public/$endpointKey'
    | '/api/integrations/webhook/$endpointKey'
    | '/api/integrations/widget/$endpointKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiCronGoogleSheetsRoute: typeof ApiCronGoogleSheetsRoute
  ApiIntegrationsGoogleCallbackRoute: typeof ApiIntegrationsGoogleCallbackRoute
  ApiIntegrationsPublicEndpointKeyRoute: typeof ApiIntegrationsPublicEndpointKeyRoute
  ApiIntegrationsWebhookEndpointKeyRoute: typeof ApiIntegrationsWebhookEndpointKeyRoute
  ApiIntegrationsWidgetEndpointKeyRoute: typeof ApiIntegrationsWidgetEndpointKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/google-sheets': {
      id: '/_authenticated/google-sheets'
      path: '/google-sheets'
      fullPath: '/google-sheets'
      preLoaderRoute: typeof AuthenticatedGoogleSheetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/earnings': {
      id: '/_authenticated/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof AuthenticatedEarningsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/delivery': {
      id: '/_authenticated/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof AuthenticatedDeliveryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/call-center': {
      id: '/_authenticated/call-center'
      path: '/call-center'
      fullPath: '/call-center'
      preLoaderRoute: typeof AuthenticatedCallCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/cron/google-sheets': {
      id: '/api/cron/google-sheets'
      path: '/api/cron/google-sheets'
      fullPath: '/api/cron/google-sheets'
      preLoaderRoute: typeof ApiCronGoogleSheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/orders/$row': {
      id: '/_authenticated/orders/$row'
      path: '/$row'
      fullPath: '/orders/$row'
      preLoaderRoute: typeof AuthenticatedOrdersRowRouteImport
      parentRoute: typeof AuthenticatedOrdersRoute
    }
    '/_authenticated/integration-test/$id': {
      id: '/_authenticated/integration-test/$id'
      path: '/integration-test/$id'
      fullPath: '/integration-test/$id'
      preLoaderRoute: typeof AuthenticatedIntegrationTestIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/$phone': {
      id: '/_authenticated/customers/$phone'
      path: '/$phone'
      fullPath: '/customers/$phone'
      preLoaderRoute: typeof AuthenticatedCustomersPhoneRouteImport
      parentRoute: typeof AuthenticatedCustomersRoute
    }
    '/api/integrations/widget/$endpointKey': {
      id: '/api/integrations/widget/$endpointKey'
      path: '/api/integrations/widget/$endpointKey'
      fullPath: '/api/integrations/widget/$endpointKey'
      preLoaderRoute: typeof ApiIntegrationsWidgetEndpointKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/webhook/$endpointKey': {
      id: '/api/integrations/webhook/$endpointKey'
      path: '/api/integrations/webhook/$endpointKey'
      fullPath: '/api/integrations/webhook/$endpointKey'
      preLoaderRoute: typeof ApiIntegrationsWebhookEndpointKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/public/$endpointKey': {
      id: '/api/integrations/public/$endpointKey'
      path: '/api/integrations/public/$endpointKey'
      fullPath: '/api/integrations/public/$endpointKey'
      preLoaderRoute: typeof ApiIntegrationsPublicEndpointKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google/callback': {
      id: '/api/integrations/google/callback'
      path: '/api/integrations/google/callback'
      fullPath: '/api/integrations/google/callback'
      preLoaderRoute: typeof ApiIntegrationsGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedCustomersRouteChildren {
  AuthenticatedCustomersPhoneRoute: typeof AuthenticatedCustomersPhoneRoute
}

const AuthenticatedCustomersRouteChildren: AuthenticatedCustomersRouteChildren =
  {
    AuthenticatedCustomersPhoneRoute: AuthenticatedCustomersPhoneRoute,
  }

const AuthenticatedCustomersRouteWithChildren =
  AuthenticatedCustomersRoute._addFileChildren(
    AuthenticatedCustomersRouteChildren,
  )

interface AuthenticatedOrdersRouteChildren {
  AuthenticatedOrdersRowRoute: typeof AuthenticatedOrdersRowRoute
}

const AuthenticatedOrdersRouteChildren: AuthenticatedOrdersRouteChildren = {
  AuthenticatedOrdersRowRoute: AuthenticatedOrdersRowRoute,
}

const AuthenticatedOrdersRouteWithChildren =
  AuthenticatedOrdersRoute._addFileChildren(AuthenticatedOrdersRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCallCenterRoute: typeof AuthenticatedCallCenterRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDeliveryRoute: typeof AuthenticatedDeliveryRoute
  AuthenticatedEarningsRoute: typeof AuthenticatedEarningsRoute
  AuthenticatedGoogleSheetsRoute: typeof AuthenticatedGoogleSheetsRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRouteWithChildren
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedIntegrationTestIdRoute: typeof AuthenticatedIntegrationTestIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCallCenterRoute: AuthenticatedCallCenterRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDeliveryRoute: AuthenticatedDeliveryRoute,
  AuthenticatedEarningsRoute: AuthenticatedEarningsRoute,
  AuthenticatedGoogleSheetsRoute: AuthenticatedGoogleSheetsRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRouteWithChildren,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedIntegrationTestIdRoute: AuthenticatedIntegrationTestIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiCronGoogleSheetsRoute: ApiCronGoogleSheetsRoute,
  ApiIntegrationsGoogleCallbackRoute: ApiIntegrationsGoogleCallbackRoute,
  ApiIntegrationsPublicEndpointKeyRoute: ApiIntegrationsPublicEndpointKeyRoute,
  ApiIntegrationsWebhookEndpointKeyRoute:
    ApiIntegrationsWebhookEndpointKeyRoute,
  ApiIntegrationsWidgetEndpointKeyRoute: ApiIntegrationsWidgetEndpointKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
